const Types = {
  FETCH_CONTACTS_START: 'contacts/FETCH_CONTACTS_START',
  FETCH_CONTACTS_SUCCESS: 'contacts/FETCH_CONTACTS_SUCCESS',
  FETCH_CONTACTS_ERROR: 'contacts/FETCH_CONTACTS_ERROR',
  ADD_CONTACT_START: 'contacts/ADD_CONTACT_START',
  ADD_CONTACT_SUCCESS: 'contacts/ADD_CONTACT_SUCCESS',
  ADD_CONTACT_ERROR: 'contacts/ADD_CONTACT_ERROR',
  DELETE_CONTACT_START: 'contacts/DELETE_CONTACT_START',
  DELETE_CONTACT_SUCCESS: 'contacts/DELETE_CONTACT_SUCCESS',
  DELETE_CONTACT_ERROR: 'contacts/DELETE_CONTACT_ERROR',
  DELETE_CONTACT: 'contacts/DELETE_CONTACT',
  FILTER_CONTACT: 'contacts/FILTER_CONTACT',
  EDIT_CONTACT_START: 'EDIT_CONTACT_START',
  EDIT_CONTACT_SUCCESS: 'EDIT_CONTACT_SUCCESS',
  EDIT_CONTACT_ERROR: 'EDIT_CONTACT_ERROR',
};

export default Types;
